# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.BidPackage do
  @moduledoc """
  Bid Package Object
  """

  @derive [Poison.Encoder]
  defstruct [
    :bid_due_date,
    :bid_email_message,
    :bid_web_message,
    :title,
    :accounting_method,
    :bid_submission_confirmation,
    :anticipated_award_date,
    :number,
    :distribution_ids,
    :blind_bidding,
    :pre_bid_walk_through_date,
    :pre_bid_walk_through_notes,
    :enable_prebid_walkthrough
  ]

  @type t :: %__MODULE__{
    :bid_due_date => DateTime.t,
    :bid_email_message => String.t,
    :bid_web_message => String.t,
    :title => String.t,
    :accounting_method => String.t | nil,
    :bid_submission_confirmation => String.t | nil,
    :anticipated_award_date => Date.t | nil,
    :number => String.t | nil,
    :distribution_ids => [integer()] | nil,
    :blind_bidding => boolean() | nil,
    :pre_bid_walk_through_date => DateTime.t | nil,
    :pre_bid_walk_through_notes => String.t | nil,
    :enable_prebid_walkthrough => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.BidPackage do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:anticipated_award_date, :date, nil, options)
  end
end

