# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.BimFileUpload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :bim_file_id,
    :document_upload_id,
    :file_version,
    :attachment,
    :created_by,
    :created_at,
    :updated_at,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :bim_file_id => integer() | nil,
    :document_upload_id => integer() | nil,
    :file_version => ProcoreRestV1APIDocumentation.Model.BimFileUploadFileVersion.t | nil,
    :attachment => ProcoreRestV1APIDocumentation.Model.BimFileUploadAttachment.t | nil,
    :created_by => ProcoreRestV1APIDocumentation.Model.BimFileUploadCreatedBy.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :metadata => ProcoreRestV1APIDocumentation.Model.BimFileUploadMetadata.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.BimFileUpload do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:file_version, :struct, ProcoreRestV1APIDocumentation.Model.BimFileUploadFileVersion, options)
    |> deserialize(:attachment, :struct, ProcoreRestV1APIDocumentation.Model.BimFileUploadAttachment, options)
    |> deserialize(:created_by, :struct, ProcoreRestV1APIDocumentation.Model.BimFileUploadCreatedBy, options)
    |> deserialize(:metadata, :struct, ProcoreRestV1APIDocumentation.Model.BimFileUploadMetadata, options)
  end
end

