# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body43 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :pdf_template_config
  ]

  @type t :: %__MODULE__{
    :pdf_template_config => ProcoreRestV1APIDocumentation.Model.PdfTemplateConfig.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body43 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:pdf_template_config, :struct, ProcoreRestV1APIDocumentation.Model.PdfTemplateConfig, options)
  end
end

