# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body135AlternatesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :position,
    :header,
    :bid_form_items
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :position => integer() | nil,
    :header => boolean() | nil,
    :bid_form_items => [ProcoreRestV1APIDocumentation.Model.Body135AlternatesInnerBidFormItemsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body135AlternatesInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bid_form_items, :list, ProcoreRestV1APIDocumentation.Model.Body135AlternatesInnerBidFormItemsInner, options)
  end
end

