# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body60 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :meeting_id,
    :meeting_topic,
    :attachments
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :meeting_id => integer(),
    :meeting_topic => ProcoreRestV1APIDocumentation.Model.MeetingTopic.t,
    :attachments => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body60 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:meeting_topic, :struct, ProcoreRestV1APIDocumentation.Model.MeetingTopic, options)
  end
end

