# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body130 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :view,
    :bim_levels
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :view => String.t | nil,
    :bim_levels => [ProcoreRestV1APIDocumentation.Model.Body128BimLevel.t]
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body130 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bim_levels, :list, ProcoreRestV1APIDocumentation.Model.Body128BimLevel, options)
  end
end

