# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body8 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :updates,
    :deletes
  ]

  @type t :: %__MODULE__{
    :updates => [ProcoreRestV1APIDocumentation.Model.UnitOfMeasureToSync.t],
    :deletes => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body8 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:updates, :list, ProcoreRestV1APIDocumentation.Model.UnitOfMeasureToSync, options)
  end
end

