# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body11 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :todo
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :todo => ProcoreRestV1APIDocumentation.Model.ToDo2.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body11 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:todo, :struct, ProcoreRestV1APIDocumentation.Model.ToDo2, options)
  end
end

