# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body108 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :budget_line_item
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :budget_line_item => ProcoreRestV1APIDocumentation.Model.BudgetLineItem.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body108 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:budget_line_item, :struct, ProcoreRestV1APIDocumentation.Model.BudgetLineItem, options)
  end
end

