# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body106 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :requisition_items
  ]

  @type t :: %__MODULE__{
    :requisition_items => [ProcoreRestV1APIDocumentation.Model.RequisitionBulkItemUpdateInner.t]
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body106 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requisition_items, :list, ProcoreRestV1APIDocumentation.Model.RequisitionBulkItemUpdateInner, options)
  end
end

