# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Body21 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :requisition_contract_item
  ]

  @type t :: %__MODULE__{
    :requisition_contract_item => ProcoreRestV1APIDocumentation.Model.RequisitionContractItem.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Body21 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requisition_contract_item, :struct, ProcoreRestV1APIDocumentation.Model.RequisitionContractItem, options)
  end
end

