# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.BudgetedProductionQuantityBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :budgeted_production_quantity
  ]

  @type t :: %__MODULE__{
    :budgeted_production_quantity => ProcoreRestV1APIDocumentation.Model.BudgetedProductionQuantity.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.BudgetedProductionQuantityBody do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:budgeted_production_quantity, :struct, ProcoreRestV1APIDocumentation.Model.BudgetedProductionQuantity, options)
  end
end

