# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ChecklistDefaultResponseSet1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :conforming_response,
    :deficient_response,
    :global,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
    :conforming_response => String.t | nil,
    :deficient_response => String.t | nil,
    :global => boolean() | nil,
    :updated_at => DateTime.t | nil,
    :created_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ChecklistDefaultResponseSet1 do
  def decode(value, _options) do
    value
  end
end

