# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ChecklistScheduleAttachment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created_at,
    :schedule_id,
    :attachment
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :created_at => DateTime.t | nil,
    :schedule_id => integer() | nil,
    :attachment => ProcoreRestV1APIDocumentation.Model.ChecklistScheduleAttachmentAttachment.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ChecklistScheduleAttachment do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attachment, :struct, ProcoreRestV1APIDocumentation.Model.ChecklistScheduleAttachmentAttachment, options)
  end
end

