# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Commitment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :number,
    :status,
    :description,
    :executed,
    :delivery_date,
    :created_at,
    :private,
    :vendor
  ]

  @type t :: %__MODULE__{
    :id => float() | nil,
    :title => String.t | nil,
    :number => String.t | nil,
    :status => String.t | nil,
    :description => String.t | nil,
    :executed => boolean() | nil,
    :delivery_date => Date.t | nil,
    :created_at => DateTime.t | nil,
    :private => boolean() | nil,
    :vendor => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Commitment do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:delivery_date, :date, nil, options)
    |> deserialize(:vendor, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor, options)
  end
end

