# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.CompanyWebhook1Hook do
  @moduledoc """
  Hook object
  """

  @derive [Poison.Encoder]
  defstruct [
    :api_version,
    :namespace,
    :destination_url,
    :destination_headers
  ]

  @type t :: %__MODULE__{
    :api_version => String.t | nil,
    :namespace => String.t | nil,
    :destination_url => String.t | nil,
    :destination_headers => ProcoreRestV1APIDocumentation.Model.CompanyWebhookHookDestinationHeaders.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.CompanyWebhook1Hook do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:destination_headers, :struct, ProcoreRestV1APIDocumentation.Model.CompanyWebhookHookDestinationHeaders, options)
  end
end

