# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.CoordinationIssueSyncResponseErrorsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :uuid,
    :title,
    :description,
    :status,
    :creation_source,
    :location_id,
    :assignee_id,
    :coordination_issue_file_id,
    :drawing_revision_id,
    :bim_model_id,
    :due_date,
    :origin,
    :attachment_upload_uuids,
    :attachments,
    :viewpoints,
    :errors
  ]

  @type t :: %__MODULE__{
    :uuid => String.t | nil,
    :title => String.t,
    :description => String.t | nil,
    :status => String.t | nil,
    :creation_source => String.t | nil,
    :location_id => integer() | nil,
    :assignee_id => integer() | nil,
    :coordination_issue_file_id => integer() | nil,
    :drawing_revision_id => integer() | nil,
    :bim_model_id => integer() | nil,
    :due_date => String.t | nil,
    :origin => ProcoreRestV1APIDocumentation.Model.Body95CoordinationIssueOrigin.t | nil,
    :attachment_upload_uuids => [String.t] | nil,
    :attachments => [String.t] | nil,
    :viewpoints => [ProcoreRestV1APIDocumentation.Model.Body95CoordinationIssueViewpointsInner.t] | nil,
    :errors => ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOf1Errors.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.CoordinationIssueSyncResponseErrorsInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:origin, :struct, ProcoreRestV1APIDocumentation.Model.Body95CoordinationIssueOrigin, options)
    |> deserialize(:viewpoints, :list, ProcoreRestV1APIDocumentation.Model.Body95CoordinationIssueViewpointsInner, options)
    |> deserialize(:errors, :struct, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOf1Errors, options)
  end
end

