# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.DrawingRevisionTermSetTermsValueInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :x,
    :y,
    :width,
    :height,
    :index
  ]

  @type t :: %__MODULE__{
    :x => integer() | nil,
    :y => integer() | nil,
    :width => integer() | nil,
    :height => integer() | nil,
    :index => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.DrawingRevisionTermSetTermsValueInner do
  def decode(value, _options) do
    value
  end
end

