# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ImageCategoryLinks do
  @moduledoc """
  Action links
  """

  @derive [Poison.Encoder]
  defstruct [
    :show,
    :delete,
    :update
  ]

  @type t :: %__MODULE__{
    :show => String.t | nil,
    :delete => String.t | nil,
    :update => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ImageCategoryLinks do
  def decode(value, _options) do
    value
  end
end

