# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ImageCategory1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :private,
    :album_cover_id
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :private => boolean() | nil,
    :album_cover_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ImageCategory1 do
  def decode(value, _options) do
    value
  end
end

