# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.InstructionScheduleImpact do
  @moduledoc """
  The Schedule Impact of the Instruction
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :value
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :value => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.InstructionScheduleImpact do
  def decode(value, _options) do
    value
  end
end

