# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ItemResponse do
  @moduledoc """
  Item Response object
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :response_option_id,
    :text_value,
    :number_value,
    :date_value
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :response_option_id => integer() | nil,
    :text_value => String.t | nil,
    :number_value => integer() | nil,
    :date_value => Date.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ItemResponse do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date_value, :date, nil, options)
  end
end

