# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.MeetingTopic do
  @moduledoc """
  Meeting topic object
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :description,
    :due_date,
    :status,
    :minutes,
    :is_private,
    :closed_at,
    :priority,
    :added_under_agenda,
    :meeting_wide_number,
    :meeting_category_id,
    :assignment_ids
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :description => String.t | nil,
    :due_date => Date.t | nil,
    :status => String.t | nil,
    :minutes => String.t | nil,
    :is_private => boolean() | nil,
    :closed_at => DateTime.t | nil,
    :priority => String.t | nil,
    :added_under_agenda => boolean() | nil,
    :meeting_wide_number => integer() | nil,
    :meeting_category_id => integer() | nil,
    :assignment_ids => [ProcoreRestV1APIDocumentation.Model.MeetingTopicAssignmentIdsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.MeetingTopic do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:due_date, :date, nil, options)
    |> deserialize(:assignment_ids, :list, ProcoreRestV1APIDocumentation.Model.MeetingTopicAssignmentIdsInner, options)
  end
end

