# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ObservationItemResponseLogBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :response_log,
    :status
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :response_log => ProcoreRestV1APIDocumentation.Model.ResponseLog.t,
    :status => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ObservationItemResponseLogBody do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:response_log, :struct, ProcoreRestV1APIDocumentation.Model.ResponseLog, options)
  end
end

