# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ProjectObservationType2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :category,
    :active
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :category => String.t | nil,
    :active => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ProjectObservationType2 do
  def decode(value, _options) do
    value
  end
end

