# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.ProjectPerson do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :is_employee,
    :employee_id,
    :origin_id
  ]

  @type t :: %__MODULE__{
    :first_name => String.t | nil,
    :last_name => String.t,
    :is_employee => boolean() | nil,
    :employee_id => String.t | nil,
    :origin_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.ProjectPerson do
  def decode(value, _options) do
    value
  end
end

