# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.PunchItemTypeBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :punch_item_type
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :punch_item_type => ProcoreRestV1APIDocumentation.Model.PunchItemType2.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.PunchItemTypeBody do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:punch_item_type, :struct, ProcoreRestV1APIDocumentation.Model.PunchItemType2, options)
  end
end

