# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsIdPatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :notes_log
  ]

  @type t :: %__MODULE__{
    :notes_log => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsIdPatchRequestNotesLog.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsIdPatchRequest do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:notes_log, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsIdPatchRequestNotesLog, options)
  end
end

