# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVendorsInactiveGet200ResponseInnerAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :_links
  ]

  @type t :: %__MODULE__{
    :_links => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVendorsInactiveGet200ResponseInnerAllOfLinks.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVendorsInactiveGet200ResponseInnerAllOf do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:_links, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVendorsInactiveGet200ResponseInnerAllOfLinks, options)
  end
end

