# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdCorrespondenceTypeItemsPatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :generic_tool_items
  ]

  @type t :: %__MODULE__{
    :generic_tool_items => [ProcoreRestV1APIDocumentation.Model.GenericToolItemsInner.t]
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdCorrespondenceTypeItemsPatchRequest do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:generic_tool_items, :list, ProcoreRestV1APIDocumentation.Model.GenericToolItemsInner, options)
  end
end

