# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdToolsPatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tools
  ]

  @type t :: %__MODULE__{
    :tools => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdToolsPatchRequestToolsInner.t]
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdToolsPatchRequest do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tools, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdToolsPatchRequestToolsInner, options)
  end
end

