# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdAccidentLogsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :comments,
    :created_at,
    :date,
    :datetime,
    :deleted_at,
    :involved_name,
    :permissions,
    :involved_company,
    :position,
    :time_hour,
    :time_minute,
    :updated_at,
    :created_by,
    :attachments
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :comments => String.t | nil,
    :created_at => DateTime.t | nil,
    :date => Date.t | nil,
    :datetime => DateTime.t | nil,
    :deleted_at => DateTime.t | nil,
    :involved_name => String.t | nil,
    :permissions => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions.t | nil,
    :involved_company => String.t | nil,
    :position => integer() | nil,
    :time_hour => integer() | nil,
    :time_minute => integer() | nil,
    :updated_at => DateTime.t | nil,
    :created_by => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :attachments => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsGet200ResponseInnerAttachmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdAccidentLogsGet200ResponseInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:permissions, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions, options)
    |> deserialize(:created_by, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:attachments, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdNotesLogsGet200ResponseInnerAttachmentsInner, options)
  end
end

