# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10PotentialChangeOrdersPost201Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :accounting_method,
    :change_order_request_id,
    :commitment_change_event_id,
    :contract_id,
    :created_at,
    :creator,
    :description,
    :due_date,
    :field_change,
    :grand_total,
    :invoiced_date,
    :line_items,
    :line_items_extended_total,
    :line_items_total,
    :number,
    :origin_data,
    :origin_id,
    :paid,
    :paid_date,
    :position,
    :prime_change_event_id,
    :private,
    :revision,
    :schedule_impact_amount,
    :status,
    :title,
    :updated_at,
    :vendor,
    :void,
    :currency_configuration
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :accounting_method => String.t | nil,
    :change_order_request_id => integer() | nil,
    :commitment_change_event_id => integer() | nil,
    :contract_id => integer() | nil,
    :created_at => DateTime.t | nil,
    :creator => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :description => String.t | nil,
    :due_date => DateTime.t | nil,
    :field_change => boolean() | nil,
    :grand_total => String.t | nil,
    :invoiced_date => Date.t | nil,
    :line_items => [map()] | nil,
    :line_items_extended_total => String.t | nil,
    :line_items_total => String.t | nil,
    :number => String.t | nil,
    :origin_data => String.t | nil,
    :origin_id => String.t | nil,
    :paid => boolean() | nil,
    :paid_date => Date.t | nil,
    :position => integer() | nil,
    :prime_change_event_id => integer() | nil,
    :private => boolean() | nil,
    :revision => integer() | nil,
    :schedule_impact_amount => integer() | nil,
    :status => String.t | nil,
    :title => String.t | nil,
    :updated_at => DateTime.t | nil,
    :vendor => ProcoreRestV1APIDocumentation.Model.RestV10PrimeContractsGet200ResponseInnerContractor.t | nil,
    :void => boolean() | nil,
    :currency_configuration => ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10PotentialChangeOrdersPost201Response do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:creator, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:invoiced_date, :date, nil, options)
    |> deserialize(:paid_date, :date, nil, options)
    |> deserialize(:vendor, :struct, ProcoreRestV1APIDocumentation.Model.RestV10PrimeContractsGet200ResponseInnerContractor, options)
    |> deserialize(:currency_configuration, :struct, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration, options)
  end
end

