# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequestPlanReference do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :plan_item_id,
    :type,
    :payload
  ]

  @type t :: %__MODULE__{
    :plan_item_id => integer(),
    :type => String.t,
    :payload => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequestPlanReferencePayload.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequestPlanReference do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:payload, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequestPlanReferencePayload, options)
  end
end

