# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :number,
    :status,
    :title,
    :description,
    :erp_status,
    :attachments,
    :adjustment_line_items,
    :created_change_event,
    :production_quantities
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :number => integer() | nil,
    :status => String.t | nil,
    :title => String.t | nil,
    :description => String.t | nil,
    :erp_status => String.t | nil,
    :attachments => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfAttachmentsInner.t] | nil,
    :adjustment_line_items => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfAdjustmentLineItemsInner.t] | nil,
    :created_change_event => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfCreatedChangeEvent.t | nil,
    :production_quantities => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfProductionQuantitiesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseData do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attachments, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfAttachmentsInner, options)
    |> deserialize(:adjustment_line_items, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfAdjustmentLineItemsInner, options)
    |> deserialize(:created_change_event, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfCreatedChangeEvent, options)
    |> deserialize(:production_quantities, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPost201ResponseDataAllOfProductionQuantitiesInner, options)
  end
end

