# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdManagedEquipmentMaintenanceLogsIdAttachmentsPostRequestManagedEquipmentMaintenanceLogsAttachment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :managed_equipment_maintenance_logs_id,
    :documents,
    :folders,
    :upload_uuids
  ]

  @type t :: %__MODULE__{
    :managed_equipment_maintenance_logs_id => integer() | nil,
    :documents => [integer()] | nil,
    :folders => [integer()] | nil,
    :upload_uuids => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdManagedEquipmentMaintenanceLogsIdAttachmentsPostRequestManagedEquipmentMaintenanceLogsAttachment do
  def decode(value, _options) do
    value
  end
end

