# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10WebhooksHooksHookIdTriggersBulkDelete207Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :success,
    :failed
  ]

  @type t :: %__MODULE__{
    :success => [integer()] | nil,
    :failed => [ProcoreRestV1APIDocumentation.Model.RestV10WebhooksHooksHookIdTriggersBulkDelete207ResponseFailedInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10WebhooksHooksHookIdTriggersBulkDelete207Response do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:failed, :list, ProcoreRestV1APIDocumentation.Model.RestV10WebhooksHooksHookIdTriggersBulkDelete207ResponseFailedInner, options)
  end
end

