# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ChangeTypesGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :abbreviation,
    :company_id,
    :change_type,
    :show_in_select
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :abbreviation => String.t | nil,
    :company_id => integer() | nil,
    :change_type => String.t | nil,
    :show_in_select => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ChangeTypesGet200ResponseInner do
  def decode(value, _options) do
    value
  end
end

