# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10PaymentApplicationsIdGet200ResponseAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :attachments,
    :g703
  ]

  @type t :: %__MODULE__{
    :attachments => [ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner.t] | nil,
    :g703 => [ProcoreRestV1APIDocumentation.Model.RestV10PaymentApplicationsIdGet200ResponseAllOfG703Inner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10PaymentApplicationsIdGet200ResponseAllOf do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attachments, :list, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner, options)
    |> deserialize(:g703, :list, ProcoreRestV1APIDocumentation.Model.RestV10PaymentApplicationsIdGet200ResponseAllOfG703Inner, options)
  end
end

