# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistListTemplatesPost201ResponseAllOfSectionsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :position,
    :items,
    :synced_to
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :position => integer() | nil,
    :items => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistListTemplatesPost201ResponseAllOfSectionsInnerAllOfItemsInner.t] | nil,
    :synced_to => ProcoreRestV1APIDocumentation.Model.RestV11ProjectsProjectIdChecklistListTemplatesIdGet200ResponseAllOfSectionsInnerAllOfSyncedTo.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistListTemplatesPost201ResponseAllOfSectionsInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:items, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistListTemplatesPost201ResponseAllOfSectionsInnerAllOfItemsInner, options)
    |> deserialize(:synced_to, :struct, ProcoreRestV1APIDocumentation.Model.RestV11ProjectsProjectIdChecklistListTemplatesIdGet200ResponseAllOfSectionsInnerAllOfSyncedTo, options)
  end
end

