# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActualProductionQuantitiesIdGetRequestActualProductionQuantity do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :quantity,
    :crew_id,
    :location_id
  ]

  @type t :: %__MODULE__{
    :quantity => float(),
    :crew_id => integer() | nil,
    :location_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdActualProductionQuantitiesIdGetRequestActualProductionQuantity do
  def decode(value, _options) do
    value
  end
end

