# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPostRequestProductionQuantitiesInner do
  @moduledoc """
  Budget Change Adjustment Production Quantity
  """

  @derive [Poison.Encoder]
  defstruct [
    :comment,
    :cost_code_id,
    :description,
    :quantity,
    :ref,
    :uom,
    :change_event_production_quantity_id
  ]

  @type t :: %__MODULE__{
    :comment => String.t | nil,
    :cost_code_id => integer(),
    :description => String.t | nil,
    :quantity => float(),
    :ref => String.t | nil,
    :uom => String.t,
    :change_event_production_quantity_id => float() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdBudgetChangesPostRequestProductionQuantitiesInner do
  def decode(value, _options) do
    value
  end
end

