# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdUploadsPost201Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :uuid,
    :url,
    :fields,
    :status,
    :segments
  ]

  @type t :: %__MODULE__{
    :uuid => String.t | nil,
    :url => String.t | nil,
    :fields => ProcoreRestV1APIDocumentation.Model.UploadFields.t | nil,
    :status => String.t | nil,
    :segments => [ProcoreRestV1APIDocumentation.Model.SegmentedUploadSegmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdUploadsPost201Response do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :struct, ProcoreRestV1APIDocumentation.Model.UploadFields, options)
    |> deserialize(:segments, :list, ProcoreRestV1APIDocumentation.Model.SegmentedUploadSegmentsInner, options)
  end
end

