# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdates do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accident_log,
    :call_log,
    :delay_log,
    :delivery_log,
    :dumpster_log,
    :equipment_log,
    :inspection_log,
    :manpower_log,
    :daily_construction_report_log,
    :notes_log,
    :plan_revision_log,
    :productivity_log,
    :quantity_log,
    :safety_violation_log,
    :timecard_entry,
    :visitor_log,
    :waste_log,
    :work_log
  ]

  @type t :: %__MODULE__{
    :accident_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :call_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :delay_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :delivery_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :dumpster_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :equipment_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :inspection_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :manpower_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :daily_construction_report_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :notes_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :plan_revision_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :productivity_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :quantity_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :safety_violation_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :timecard_entry => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :visitor_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :waste_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil,
    :work_log => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdates do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accident_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:call_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:delay_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:delivery_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:dumpster_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:equipment_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:inspection_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:manpower_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:daily_construction_report_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:notes_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:plan_revision_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:productivity_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:quantity_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:safety_violation_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:timecard_entry, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:visitor_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:waste_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
    |> deserialize(:work_log, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatchRequestUpdatesAccidentLogInner, options)
  end
end

