# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10RequisitionsGet200ResponseInnerCurrencyConfiguration do
  @moduledoc """
  Requisition (Subcontractor Invoice) Currency Configuration
  """

  @derive [Poison.Encoder]
  defstruct [
    :currency_iso_code
  ]

  @type t :: %__MODULE__{
    :currency_iso_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10RequisitionsGet200ResponseInnerCurrencyConfiguration do
  def decode(value, _options) do
    value
  end
end

