# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdIncidentsPostRequestIncident do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :event_date,
    :distribution_member_ids,
    :private,
    :recordable,
    :status,
    :time_unknown,
    :title,
    :contributing_behavior_id,
    :contributing_condition_id,
    :hazard_id,
    :location_id,
    :environmentals,
    :injuries,
    :near_misses,
    :property_damages,
    :witness_statements_attributes,
    :upload_uuids,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :event_date => DateTime.t | nil,
    :distribution_member_ids => [integer()] | nil,
    :private => boolean() | nil,
    :recordable => boolean() | nil,
    :status => String.t | nil,
    :time_unknown => boolean() | nil,
    :title => String.t | nil,
    :contributing_behavior_id => integer() | nil,
    :contributing_condition_id => integer() | nil,
    :hazard_id => integer() | nil,
    :location_id => integer() | nil,
    :environmentals => [ProcoreRestV1APIDocumentation.Model.IncidentEnvironmentalUpdateParameters.t] | nil,
    :injuries => [ProcoreRestV1APIDocumentation.Model.IncidentInjuryUpdateParameters.t] | nil,
    :near_misses => [ProcoreRestV1APIDocumentation.Model.IncidentNearMissUpdateParameters.t] | nil,
    :property_damages => [ProcoreRestV1APIDocumentation.Model.IncidentPropertyDamageUpdateParameters.t] | nil,
    :witness_statements_attributes => [ProcoreRestV1APIDocumentation.Model.IncidentWitnessStatementUpdateParameters1.t] | nil,
    :upload_uuids => [String.t] | nil,
    :"custom_field_%{custom_field_definition_id}" => ProcoreRestV1APIDocumentation.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdIncidentsPostRequestIncident do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:environmentals, :list, ProcoreRestV1APIDocumentation.Model.IncidentEnvironmentalUpdateParameters, options)
    |> deserialize(:injuries, :list, ProcoreRestV1APIDocumentation.Model.IncidentInjuryUpdateParameters, options)
    |> deserialize(:near_misses, :list, ProcoreRestV1APIDocumentation.Model.IncidentNearMissUpdateParameters, options)
    |> deserialize(:property_damages, :list, ProcoreRestV1APIDocumentation.Model.IncidentPropertyDamageUpdateParameters, options)
    |> deserialize(:witness_statements_attributes, :list, ProcoreRestV1APIDocumentation.Model.IncidentWitnessStatementUpdateParameters1, options)
    |> deserialize(:"custom_field_%{custom_field_definition_id}", :struct, ProcoreRestV1APIDocumentation.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId, options)
  end
end

