# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdProgramsPost201ResponseAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :zip,
    :longitude,
    :latitude,
    :projects
  ]

  @type t :: %__MODULE__{
    :zip => String.t | nil,
    :longitude => String.t | nil,
    :latitude => String.t | nil,
    :projects => [ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdProgramsPost201ResponseAllOfProjectsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdProgramsPost201ResponseAllOf do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:projects, :list, ProcoreRestV1APIDocumentation.Model.RestV10CompaniesCompanyIdProgramsPost201ResponseAllOfProjectsInner, options)
  end
end

