# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLog do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :comment,
    :created_at,
    :created_by_collaborator,
    :custom_fields,
    :date,
    :datetime,
    :daily_log_header_id,
    :deleted_at,
    :is_issue_day,
    :permissions,
    :position,
    :updated_at,
    :status,
    :attachments,
    :created_by,
    :location
  ]

  @type t :: %__MODULE__{
    :id => float() | nil,
    :comment => String.t | nil,
    :created_at => DateTime.t | nil,
    :created_by_collaborator => boolean() | nil,
    :custom_fields => map() | nil,
    :date => Date.t | nil,
    :datetime => DateTime.t | nil,
    :daily_log_header_id => float() | nil,
    :deleted_at => String.t | nil,
    :is_issue_day => String.t | nil,
    :permissions => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogPermissions.t | nil,
    :position => float() | nil,
    :updated_at => DateTime.t | nil,
    :status => String.t | nil,
    :attachments => [map()] | nil,
    :created_by => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy.t | nil,
    :location => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLog do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:permissions, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogPermissions, options)
    |> deserialize(:created_by, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy, options)
  end
end

