# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedProcoreItemsInnerAllOf do
  @moduledoc """
  CoordinationIssue Procore Item Association details
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :coordination_issue_id,
    :item_id,
    :item_type,
    :item_url
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :coordination_issue_id => integer() | nil,
    :item_id => integer() | nil,
    :item_type => String.t | nil,
    :item_url => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedProcoreItemsInnerAllOf do
  def decode(value, _options) do
    value
  end
end

