# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ToolsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :engine_name,
    :is_active,
    :position,
    :required,
    :user_access_level,
    :provider_id,
    :provider_type
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :engine_name => String.t | nil,
    :is_active => boolean() | nil,
    :position => integer() | nil,
    :required => boolean() | nil,
    :user_access_level => String.t | nil,
    :provider_id => integer() | nil,
    :provider_type => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ToolsGet200ResponseInner do
  def decode(value, _options) do
    value
  end
end

