# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsEmailsGet200ResponseEmailsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :communication_id,
    :subject,
    :private,
    :attachments,
    :bcc_distribution,
    :body,
    :cc_distribution,
    :distribution,
    :email_sent_at,
    :login_information
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :communication_id => integer() | nil,
    :subject => String.t | nil,
    :private => boolean() | nil,
    :attachments => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsEmailsGet200ResponseEmailsInnerAttachmentsInner.t] | nil,
    :bcc_distribution => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner.t] | nil,
    :body => String.t | nil,
    :cc_distribution => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner.t] | nil,
    :distribution => [ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner.t] | nil,
    :email_sent_at => DateTime.t | nil,
    :login_information => ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerLoginInformation.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsEmailsGet200ResponseEmailsInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attachments, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsEmailsGet200ResponseEmailsInnerAttachmentsInner, options)
    |> deserialize(:bcc_distribution, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner, options)
    |> deserialize(:cc_distribution, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner, options)
    |> deserialize(:distribution, :list, ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerBccDistributionInner, options)
    |> deserialize(:login_information, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectProjectIdEmailCommunicationsIdGet200ResponseEmailsInnerLoginInformation, options)
  end
end

