# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistSchedulesCalculateFirstInspectionCreatedAtGetRequestSchedule do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :starts_at,
    :ends_at,
    :frequency,
    :days_created_before_due_date
  ]

  @type t :: %__MODULE__{
    :starts_at => DateTime.t,
    :ends_at => DateTime.t,
    :frequency => String.t,
    :days_created_before_due_date => integer()
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdChecklistSchedulesCalculateFirstInspectionCreatedAtGetRequestSchedule do
  def decode(value, _options) do
    value
  end
end

