# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdIncidentsNearMissesPostRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :near_miss
  ]

  @type t :: %__MODULE__{
    :near_miss => ProcoreRestV1APIDocumentation.Model.IncidentNearMissCreateParameters.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdIncidentsNearMissesPostRequest do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:near_miss, :struct, ProcoreRestV1APIDocumentation.Model.IncidentNearMissCreateParameters, options)
  end
end

