# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWeatherLogsPostRequestWeatherLog do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :is_weather_delay,
    :sky,
    :temperature,
    :average,
    :wind,
    :ground,
    :calamity,
    :precipitation,
    :comments,
    :time
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :is_weather_delay => integer() | nil,
    :sky => String.t | nil,
    :temperature => String.t | nil,
    :average => String.t | nil,
    :wind => String.t | nil,
    :ground => String.t | nil,
    :calamity => String.t | nil,
    :precipitation => String.t | nil,
    :comments => String.t | nil,
    :time => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWeatherLogsPostRequestWeatherLog do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end

