# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RfiUpdateBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rfi
  ]

  @type t :: %__MODULE__{
    :rfi => ProcoreRestV1APIDocumentation.Model.RfiUpdateBodyRfi.t
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RfiUpdateBody do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rfi, :struct, ProcoreRestV1APIDocumentation.Model.RfiUpdateBodyRfi, options)
  end
end

