# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :cost_code_biller_name,
    :cost_code,
    :cost_code_is_budgeted,
    :description,
    :event_id,
    :line_item_type,
    :rom,
    :contract,
    :links,
    :statuses,
    :number,
    :status,
    :title,
    :vendor,
    :commitment_contract_cost,
    :commitment_pco_cost,
    :budget_mod_amount,
    :budget_mod,
    :prime_pco_cost,
    :rfq_amount,
    :rfq_status
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :cost_code_biller_name => String.t | nil,
    :cost_code => ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode.t | nil,
    :cost_code_is_budgeted => boolean() | nil,
    :description => String.t | nil,
    :event_id => integer() | nil,
    :line_item_type => ProcoreRestV1APIDocumentation.Model.LineItemType.t | nil,
    :rom => integer() | nil,
    :contract => ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerContract.t | nil,
    :links => ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerLinks.t | nil,
    :statuses => ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerStatuses.t | nil,
    :number => String.t | nil,
    :status => String.t | nil,
    :title => String.t | nil,
    :vendor => ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor.t | nil,
    :commitment_contract_cost => String.t | nil,
    :commitment_pco_cost => String.t | nil,
    :budget_mod_amount => String.t | nil,
    :budget_mod => ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerBudgetMod.t | nil,
    :prime_pco_cost => String.t | nil,
    :rfq_amount => String.t | nil,
    :rfq_status => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:cost_code, :struct, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode, options)
    |> deserialize(:line_item_type, :struct, ProcoreRestV1APIDocumentation.Model.LineItemType, options)
    |> deserialize(:contract, :struct, ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerContract, options)
    |> deserialize(:links, :struct, ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerLinks, options)
    |> deserialize(:statuses, :struct, ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerStatuses, options)
    |> deserialize(:vendor, :struct, ProcoreRestV1APIDocumentation.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor, options)
    |> deserialize(:budget_mod, :struct, ProcoreRestV1APIDocumentation.Model.RfqChangeEventChangeEventLineItemsInnerBudgetMod, options)
  end
end

