# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.SsovSourceLines do
  @moduledoc """
  Line Item (when the 'ssov_source_lines' view is requested)
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :amount,
    :description,
    :position,
    :wbs_code,
    :currency_configuration
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :amount => String.t | nil,
    :description => String.t | nil,
    :position => integer() | nil,
    :wbs_code => ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode.t | nil,
    :currency_configuration => ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.SsovSourceLines do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:wbs_code, :struct, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode, options)
    |> deserialize(:currency_configuration, :struct, ProcoreRestV1APIDocumentation.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration, options)
  end
end

