# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Task1 do
  @moduledoc """
  Task object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :start,
    :finish,
    :actual_start,
    :actual_finish,
    :percentage,
    :critical_path,
    :milestone,
    :row_number,
    :has_children,
    :source_uid,
    :parent_id,
    :full_outline_path,
    :activity_id,
    :wbs,
    :schedule_duration,
    :resource_ids,
    :notes,
    :baseline_start,
    :baseline_finish,
    :start_variance,
    :finish_variance,
    :manually_edited
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :start => DateTime.t | nil,
    :finish => DateTime.t | nil,
    :actual_start => DateTime.t | nil,
    :actual_finish => DateTime.t | nil,
    :percentage => integer() | nil,
    :critical_path => boolean() | nil,
    :milestone => boolean() | nil,
    :row_number => integer() | nil,
    :has_children => boolean() | nil,
    :source_uid => String.t | nil,
    :parent_id => integer() | nil,
    :full_outline_path => String.t | nil,
    :activity_id => String.t | nil,
    :wbs => String.t | nil,
    :schedule_duration => float() | nil,
    :resource_ids => [integer()] | nil,
    :notes => String.t | nil,
    :baseline_start => DateTime.t | nil,
    :baseline_finish => DateTime.t | nil,
    :start_variance => float() | nil,
    :finish_variance => float() | nil,
    :manually_edited => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Task1 do
  def decode(value, _options) do
    value
  end
end

