# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.TimecardEntriesTimecardEntriesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :approval_status,
    :billable,
    :cost_code_id,
    :crew_id,
    :date,
    :description,
    :hours,
    :location_id,
    :origin_id,
    :origin_data,
    :party_id,
    :project_id,
    :sub_job_id,
    :time_in,
    :time_out,
    :timesheet_id,
    :timecard_time_type_id,
    :user_id,
    :work_classification_id
  ]

  @type t :: %__MODULE__{
    :approval_status => String.t | nil,
    :billable => boolean() | nil,
    :cost_code_id => integer() | nil,
    :crew_id => integer() | nil,
    :date => Date.t | nil,
    :description => String.t | nil,
    :hours => integer() | nil,
    :location_id => integer() | nil,
    :origin_id => integer() | nil,
    :origin_data => String.t | nil,
    :party_id => integer() | nil,
    :project_id => integer() | nil,
    :sub_job_id => integer() | nil,
    :time_in => DateTime.t | nil,
    :time_out => DateTime.t | nil,
    :timesheet_id => integer() | nil,
    :timecard_time_type_id => integer() | nil,
    :user_id => integer() | nil,
    :work_classification_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.TimecardEntriesTimecardEntriesInner do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end

