# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreRestV1APIDocumentation.Model.Upload1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :segments
  ]

  @type t :: %__MODULE__{
    :segments => [ProcoreRestV1APIDocumentation.Model.UploadSegmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreRestV1APIDocumentation.Model.Upload1 do
  import ProcoreRestV1APIDocumentation.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:segments, :list, ProcoreRestV1APIDocumentation.Model.UploadSegmentsInner, options)
  end
end

