# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOf do
  @moduledoc """
  Line Item
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :amount,
    :company,
    :cost_code,
    :created_at,
    :description,
    :extended_type,
    :holder,
    :line_item_type,
    :origin_data,
    :origin_id,
    :position,
    :project,
    :quantity,
    :tax_code_id,
    :total_amount,
    :extended_amount,
    :unit_cost,
    :uom,
    :updated_at,
    :change_event_line_item
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :amount => String.t | nil,
    :company => ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany.t | nil,
    :cost_code => ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode.t | nil,
    :created_at => DateTime.t | nil,
    :description => String.t | nil,
    :extended_type => String.t | nil,
    :holder => ProcoreV1API.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOfHolder.t | nil,
    :line_item_type => ProcoreV1API.Model.LineItemType.t | nil,
    :origin_data => String.t | nil,
    :origin_id => String.t | nil,
    :position => integer() | nil,
    :project => ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerProject.t | nil,
    :quantity => String.t | nil,
    :tax_code_id => integer() | nil,
    :total_amount => String.t | nil,
    :extended_amount => String.t | nil,
    :unit_cost => String.t | nil,
    :uom => String.t | nil,
    :updated_at => DateTime.t | nil,
    :change_event_line_item => ProcoreV1API.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseEntitiesInnerChangeEventLineItem.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOf do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:company, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany, options)
    |> deserialize(:cost_code, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode, options)
    |> deserialize(:holder, :struct, ProcoreV1API.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOfHolder, options)
    |> deserialize(:line_item_type, :struct, ProcoreV1API.Model.LineItemType, options)
    |> deserialize(:project, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerProject, options)
    |> deserialize(:change_event_line_item, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseEntitiesInnerChangeEventLineItem, options)
  end
end

