# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.BimModelRevisionPlanBatchCreateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :bim_model_revision_plans,
    :errors
  ]

  @type t :: %__MODULE__{
    :bim_model_revision_plans => [ProcoreV1API.Model.RestV10BimModelRevisionPlansGet200ResponseInner.t] | nil,
    :errors => [ProcoreV1API.Model.BimModelRevisionPlanBatchCreateResponseErrorsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.BimModelRevisionPlanBatchCreateResponse do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bim_model_revision_plans, :list, ProcoreV1API.Model.RestV10BimModelRevisionPlansGet200ResponseInner, options)
    |> deserialize(:errors, :list, ProcoreV1API.Model.BimModelRevisionPlanBatchCreateResponseErrorsInner, options)
  end
end

