# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.BimFileExtractionItemArtifact do
  @moduledoc """
  Artifact extracted from a 3d model. Only one of grid, mobile_format, properties, web_format and object_search will have data associated to the artifact extracted
  """

  @derive [Poison.Encoder]
  defstruct [
    :grid,
    :mobile_format,
    :properties,
    :web_format,
    :object_search
  ]

  @type t :: %__MODULE__{
    :grid => ProcoreV1API.Model.BimFileExtractionItemArtifactGrid.t | nil,
    :mobile_format => ProcoreV1API.Model.RestV11ProjectsProjectIdDailyLogsWeatherLogsGet200ResponseInnerAttachmentsInner.t | nil,
    :properties => ProcoreV1API.Model.RestV11ProjectsProjectIdDailyLogsWeatherLogsGet200ResponseInnerAttachmentsInner.t | nil,
    :web_format => ProcoreV1API.Model.BimFileExtractionItemArtifactWebFormat.t | nil,
    :object_search => ProcoreV1API.Model.BimFileExtractionItemArtifactObjectSearch.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.BimFileExtractionItemArtifact do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:grid, :struct, ProcoreV1API.Model.BimFileExtractionItemArtifactGrid, options)
    |> deserialize(:mobile_format, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdDailyLogsWeatherLogsGet200ResponseInnerAttachmentsInner, options)
    |> deserialize(:properties, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdDailyLogsWeatherLogsGet200ResponseInnerAttachmentsInner, options)
    |> deserialize(:web_format, :struct, ProcoreV1API.Model.BimFileExtractionItemArtifactWebFormat, options)
    |> deserialize(:object_search, :struct, ProcoreV1API.Model.BimFileExtractionItemArtifactObjectSearch, options)
  end
end

