# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.BimFileUploadFileVersion do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :file_id
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :file_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.BimFileUploadFileVersion do
  def decode(value, _options) do
    value
  end
end

