# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body135BaseBidInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :position,
    :header,
    :bid_form_items
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :position => integer() | nil,
    :header => boolean() | nil,
    :bid_form_items => [ProcoreV1API.Model.Body135BaseBidInnerBidFormItemsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body135BaseBidInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bid_form_items, :list, ProcoreV1API.Model.Body135BaseBidInnerBidFormItemsInner, options)
  end
end

