# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body65 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :location
  ]

  @type t :: %__MODULE__{
    :location => ProcoreV1API.Model.Location4.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body65 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:location, :struct, ProcoreV1API.Model.Location4, options)
  end
end

