# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body111 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :budget_line_item
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :budget_line_item => ProcoreV1API.Model.BudgetLineItem3.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body111 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:budget_line_item, :struct, ProcoreV1API.Model.BudgetLineItem3, options)
  end
end

