# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body98 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :deletes
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :deletes => [ProcoreV1API.Model.Body98DeletesInner.t]
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body98 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:deletes, :list, ProcoreV1API.Model.Body98DeletesInner, options)
  end
end

