# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body16 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :schedule_type
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :schedule_type => ProcoreV1API.Model.ScheduleType1.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body16 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:schedule_type, :struct, ProcoreV1API.Model.ScheduleType1, options)
  end
end

