# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :line_item
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :line_item => ProcoreV1API.Model.LineItem.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body3 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:line_item, :struct, ProcoreV1API.Model.LineItem, options)
  end
end

