# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :attachments,
    :work_order_contract
  ]

  @type t :: %__MODULE__{
    :project_id => integer(),
    :attachments => [String.t] | nil,
    :work_order_contract => ProcoreV1API.Model.WorkOrderContract.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:work_order_contract, :struct, ProcoreV1API.Model.WorkOrderContract, options)
  end
end

