# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body20FilesInner do
  @moduledoc """
  File associated with the requisition
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :id,
    :url
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => integer(),
    :url => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body20FilesInner do
  def decode(value, _options) do
    value
  end
end

