# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body74 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :image_category
  ]

  @type t :: %__MODULE__{
    :image_category => ProcoreV1API.Model.ImageCategory1.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body74 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:image_category, :struct, ProcoreV1API.Model.ImageCategory1, options)
  end
end

