# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body128BimLevel do
  @moduledoc """
  BIM Level
  """

  @derive [Poison.Encoder]
  defstruct [
    :elevation,
    :bim_file_id,
    :location_id
  ]

  @type t :: %__MODULE__{
    :elevation => float(),
    :bim_file_id => integer(),
    :location_id => integer()
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body128BimLevel do
  def decode(value, _options) do
    value
  end
end

