# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body80 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :drawing
  ]

  @type t :: %__MODULE__{
    :drawing => ProcoreV1API.Model.Drawing.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body80 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:drawing, :struct, ProcoreV1API.Model.Drawing, options)
  end
end

