# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Body41 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :program
  ]

  @type t :: %__MODULE__{
    :program => ProcoreV1API.Model.Program1.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Body41 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:program, :struct, ProcoreV1API.Model.Program1, options)
  end
end

