# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.ChecklistInspectionItemObservation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :checklist_item_id,
    :checklist_list_id,
    :created_at,
    :updated_at,
    :created_by
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :checklist_item_id => integer() | nil,
    :checklist_list_id => integer() | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :created_by => ProcoreV1API.Model.RestV10RequisitionsGet200ResponseInnerCreatedBy.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.ChecklistInspectionItemObservation do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:created_by, :struct, ProcoreV1API.Model.RestV10RequisitionsGet200ResponseInnerCreatedBy, options)
  end
end

