# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.ChecklistResponseBody2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :response
  ]

  @type t :: %__MODULE__{
    :response => ProcoreV1API.Model.Response2.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.ChecklistResponseBody2 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:response, :struct, ProcoreV1API.Model.Response2, options)
  end
end

