# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.ConfigurableFieldSet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :type,
    :category,
    :class_name,
    :fields,
    :sections,
    :inspection_type_id,
    :generic_tool_id,
    :action_plan_type_id
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :type => String.t | nil,
    :category => String.t | nil,
    :class_name => String.t | nil,
    :fields => ProcoreV1API.Model.ConfigurableFieldSetFields.t | nil,
    :sections => [ProcoreV1API.Model.ConfigurableFieldSetSectionsInner.t] | nil,
    :inspection_type_id => integer() | nil,
    :generic_tool_id => integer() | nil,
    :action_plan_type_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.ConfigurableFieldSet do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :struct, ProcoreV1API.Model.ConfigurableFieldSetFields, options)
    |> deserialize(:sections, :list, ProcoreV1API.Model.ConfigurableFieldSetSectionsInner, options)
  end
end

