# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :old_assignee,
    :new_assignee,
    :comment,
    :created_by
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :old_assignee => ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsOldAssignee.t | nil,
    :new_assignee => ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsNewAssignee.t | nil,
    :comment => ProcoreV1API.Model.Comment.t | nil,
    :created_by => ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsCreatedBy.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetails do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:old_assignee, :struct, ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsOldAssignee, options)
    |> deserialize(:new_assignee, :struct, ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsNewAssignee, options)
    |> deserialize(:comment, :struct, ProcoreV1API.Model.Comment, options)
    |> deserialize(:created_by, :struct, ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetailsCreatedBy, options)
  end
end

