# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Correspondence do
  @moduledoc """
  Correspondence
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :bid_package_id,
    :bid_package_title,
    :created_at,
    :subject
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :bid_package_id => integer() | nil,
    :bid_package_title => String.t | nil,
    :created_at => String.t | nil,
    :subject => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Correspondence do
  def decode(value, _options) do
    value
  end
end

