# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Drawing1 do
  @moduledoc """
  Drawing
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :title,
    :obsolete,
    :drawing_discipline,
    :ordered_revision_ids
  ]

  @type t :: %__MODULE__{
    :number => String.t | nil,
    :title => String.t | nil,
    :obsolete => boolean() | nil,
    :drawing_discipline => ProcoreV1API.Model.Drawing1DrawingDiscipline.t | nil,
    :ordered_revision_ids => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Drawing1 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:drawing_discipline, :struct, ProcoreV1API.Model.Drawing1DrawingDiscipline, options)
  end
end

