# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.GenericToolItem1ScheduleImpact do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :value
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :value => float() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.GenericToolItem1ScheduleImpact do
  def decode(value, _options) do
    value
  end
end

