# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.IncidentWitnessStatementUpdateParameters do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :statement,
    :date_received,
    :witness_id,
    :upload_uuids,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
    :statement => String.t | nil,
    :date_received => Date.t | nil,
    :witness_id => integer() | nil,
    :upload_uuids => [String.t] | nil,
    :"custom_field_%{custom_field_definition_id}" => ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.IncidentWitnessStatementUpdateParameters do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date_received, :date, nil, options)
    |> deserialize(:"custom_field_%{custom_field_definition_id}", :struct, ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId, options)
  end
end

