# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.PdfTemplateConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :template_name,
    :default_project,
    :pdf_config_options
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :template_name => String.t | nil,
    :default_project => boolean() | nil,
    :pdf_config_options => ProcoreV1API.Model.PdfTemplateConfigPdfConfigOptions.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.PdfTemplateConfig do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:pdf_config_options, :struct, ProcoreV1API.Model.PdfTemplateConfigPdfConfigOptions, options)
  end
end

