# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.ProjectIncidentConfiguration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :private_by_default,
    :default_distribution
  ]

  @type t :: %__MODULE__{
    :project_id => integer() | nil,
    :private_by_default => boolean() | nil,
    :default_distribution => [ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.ProjectIncidentConfiguration do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:default_distribution, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
  end
end

