# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RequisitionSubcontractorInvoice do
  @moduledoc """
  Requisition (Subcontractor Invoice)
  """

  @derive [Poison.Encoder]
  defstruct [
    :period_id,
    :requisition_start,
    :requisition_end,
    :billing_date,
    :final,
    :invoice_number,
    :payment_date,
    :origin_data,
    :origin_id,
    :status,
    :submitted_at,
    :comment,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
    :period_id => integer() | nil,
    :requisition_start => Date.t | nil,
    :requisition_end => Date.t | nil,
    :billing_date => Date.t | nil,
    :final => boolean() | nil,
    :invoice_number => String.t | nil,
    :payment_date => Date.t | nil,
    :origin_data => String.t | nil,
    :origin_id => String.t | nil,
    :status => String.t | nil,
    :submitted_at => Date.t | nil,
    :comment => String.t | nil,
    :"custom_field_%{custom_field_definition_id}" => ProcoreV1API.Model.WorkOrderContractCustomFieldCustomFieldDefinitionId.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RequisitionSubcontractorInvoice do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requisition_start, :date, nil, options)
    |> deserialize(:requisition_end, :date, nil, options)
    |> deserialize(:billing_date, :date, nil, options)
    |> deserialize(:payment_date, :date, nil, options)
    |> deserialize(:submitted_at, :date, nil, options)
    |> deserialize(:"custom_field_%{custom_field_definition_id}", :struct, ProcoreV1API.Model.WorkOrderContractCustomFieldCustomFieldDefinitionId, options)
  end
end

