# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompanyBaseUrlGet200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :zone,
    :web_base_url
  ]

  @type t :: %__MODULE__{
    :zone => String.t | nil,
    :web_base_url => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompanyBaseUrlGet200Response do
  def decode(value, _options) do
    value
  end
end

