# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdHazardsPostRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :hazard
  ]

  @type t :: %__MODULE__{
    :hazard => ProcoreV1API.Model.RestV10CompaniesCompanyIdHazardsPostRequestHazard.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdHazardsPostRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:hazard, :struct, ProcoreV1API.Model.RestV10CompaniesCompanyIdHazardsPostRequestHazard, options)
  end
end

