# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdRfisGet200ResponseInnerAllOfQuestionsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :body,
    :errors
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :body => String.t | nil,
    :errors => [ProcoreV1API.Model.RestV10CompaniesCompanyIdProjectsProjectIdTaskItemCommentsPost403Response.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdRfisGet200ResponseInnerAllOfQuestionsInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, ProcoreV1API.Model.RestV10CompaniesCompanyIdProjectsProjectIdTaskItemCommentsPost403Response, options)
  end
end

