# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdIncidentsWorkActivitiesBulkUpdatePatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :work_activity
  ]

  @type t :: %__MODULE__{
    :work_activity => ProcoreV1API.Model.RestV10CompaniesCompanyIdIncidentsWorkActivitiesBulkUpdatePatchRequestWorkActivity.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdIncidentsWorkActivitiesBulkUpdatePatchRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:work_activity, :struct, ProcoreV1API.Model.RestV10CompaniesCompanyIdIncidentsWorkActivitiesBulkUpdatePatchRequestWorkActivity, options)
  end
end

