# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedObservationItemsInner do
  @moduledoc """
  CoordinationIssue linked Observation Item
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :number,
    :personal,
    :title,
    :url,
    :created_by_id
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :number => String.t | nil,
    :personal => boolean() | nil,
    :title => String.t | nil,
    :url => String.t | nil,
    :created_by_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedObservationItemsInner do
  def decode(value, _options) do
    value
  end
end

