# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdMeetingTemplatesGet200ResponseInnerAgendasInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :category,
    :description,
    :attachments
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :title => String.t | nil,
    :category => String.t | nil,
    :description => String.t | nil,
    :attachments => [ProcoreV1API.Model.RestV10CompaniesCompanyIdMeetingTemplatesGet200ResponseInnerAgendasInnerAttachmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdMeetingTemplatesGet200ResponseInnerAgendasInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attachments, :list, ProcoreV1API.Model.RestV10CompaniesCompanyIdMeetingTemplatesGet200ResponseInnerAgendasInnerAttachmentsInner, options)
  end
end

