# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10PrimeContractsGet200ResponseInnerContractorAllOf1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :children_count,
    :legal_name,
    :parent,
    :trades,
    :bidding_distribution,
    :bidding
  ]

  @type t :: %__MODULE__{
    :children_count => integer() | nil,
    :legal_name => String.t | nil,
    :parent => ProcoreV1API.Model.ExtendedViewParent.t | nil,
    :trades => [ProcoreV1API.Model.Trade2.t] | nil,
    :bidding_distribution => [ProcoreV1API.Model.ArrayOfTaskItemsThatWereSentOutInnerAllOfAssignee.t] | nil,
    :bidding => ProcoreV1API.Model.ExtendedViewBidding.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10PrimeContractsGet200ResponseInnerContractorAllOf1 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:parent, :struct, ProcoreV1API.Model.ExtendedViewParent, options)
    |> deserialize(:trades, :list, ProcoreV1API.Model.Trade2, options)
    |> deserialize(:bidding_distribution, :list, ProcoreV1API.Model.ArrayOfTaskItemsThatWereSentOutInnerAllOfAssignee, options)
    |> deserialize(:bidding, :struct, ProcoreV1API.Model.ExtendedViewBidding, options)
  end
end

