# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10BudgetViewsBudgetViewIdSummaryRowsGet200ResponseInner do
  @moduledoc """
  Budget View Summary Row
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :biller_type,
    :original_budget_amount,
    :budget_modifications,
    :budget_forecast
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :biller_type => String.t | nil,
    :original_budget_amount => String.t | nil,
    :budget_modifications => String.t | nil,
    :budget_forecast => ProcoreV1API.Model.RestV10BudgetViewsBudgetViewIdSummaryRowsGet200ResponseInnerBudgetForecast.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10BudgetViewsBudgetViewIdSummaryRowsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:budget_forecast, :struct, ProcoreV1API.Model.RestV10BudgetViewsBudgetViewIdSummaryRowsGet200ResponseInnerBudgetForecast, options)
  end
end

