# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdEquipmentLogsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created_at,
    :date,
    :datetime,
    :deleted_at,
    :hours_idle,
    :hours_operating,
    :inspected,
    :inspection_hour,
    :inspection_minute,
    :notes,
    :position,
    :updated_at,
    :created_by,
    :location,
    :cost_code,
    :equipment,
    :permissions,
    :custom_fields,
    :attachments
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :created_at => DateTime.t | nil,
    :date => Date.t | nil,
    :datetime => DateTime.t | nil,
    :deleted_at => DateTime.t | nil,
    :hours_idle => String.t | nil,
    :hours_operating => String.t | nil,
    :inspected => boolean() | nil,
    :inspection_hour => integer() | nil,
    :inspection_minute => integer() | nil,
    :notes => String.t | nil,
    :position => integer() | nil,
    :updated_at => DateTime.t | nil,
    :created_by => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :location => ProcoreV1API.Model.Location2.t | nil,
    :cost_code => ProcoreV1API.Model.TimesheetEntriesCostCode.t | nil,
    :equipment => ProcoreV1API.Model.RestV10ProjectsProjectIdEquipmentLogsGet200ResponseInnerEquipment.t | nil,
    :permissions => ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions.t | nil,
    :custom_fields => ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerCustomFields.t | nil,
    :attachments => [ProcoreV1API.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet200ResponseInnerAttachmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdEquipmentLogsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:created_by, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:location, :struct, ProcoreV1API.Model.Location2, options)
    |> deserialize(:cost_code, :struct, ProcoreV1API.Model.TimesheetEntriesCostCode, options)
    |> deserialize(:equipment, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdEquipmentLogsGet200ResponseInnerEquipment, options)
    |> deserialize(:permissions, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions, options)
    |> deserialize(:custom_fields, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerCustomFields, options)
    |> deserialize(:attachments, :list, ProcoreV1API.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet200ResponseInnerAttachmentsInner, options)
  end
end

