# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlan do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :description,
    :private,
    :location_id,
    :manager_id,
    :plan_type_id,
    :status_id,
    :plan_approvers_attributes,
    :plan_receivers_attributes,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :description => String.t | nil,
    :private => boolean() | nil,
    :location_id => integer() | nil,
    :manager_id => integer() | nil,
    :plan_type_id => integer() | nil,
    :status_id => integer() | nil,
    :plan_approvers_attributes => [ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlanPlanApproversAttributesInner.t] | nil,
    :plan_receivers_attributes => [ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlanPlanReceiversAttributesInner.t] | nil,
    :"custom_field_%{custom_field_definition_id}" => ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlan do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:plan_approvers_attributes, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlanPlanApproversAttributesInner, options)
    |> deserialize(:plan_receivers_attributes, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlansIdPatchRequestPlanPlanReceiversAttributesInner, options)
    |> deserialize(:"custom_field_%{custom_field_definition_id}", :struct, ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId, options)
  end
end

