# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :actual_delivery_date,
    :attachments,
    :confirmed_delivery_date,
    :cost_code,
    :created_at,
    :custom_textarea_1,
    :custom_textfield_1,
    :deleted_at,
    :description,
    :design_team_review_time,
    :distribution_members,
    :internal_review_time,
    :lead_time,
    :required_on_site_date,
    :scheduled_task,
    :source_submittal_log_id,
    :distributed_submittals
  ]

  @type t :: %__MODULE__{
    :actual_delivery_date => Date.t | nil,
    :attachments => [ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner.t] | nil,
    :confirmed_delivery_date => Date.t | nil,
    :cost_code => ProcoreV1API.Model.TimesheetEntriesCostCode.t | nil,
    :created_at => DateTime.t | nil,
    :custom_textarea_1 => String.t | nil,
    :custom_textfield_1 => String.t | nil,
    :deleted_at => DateTime.t | nil,
    :description => String.t | nil,
    :design_team_review_time => integer() | nil,
    :distribution_members => [ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t] | nil,
    :internal_review_time => integer() | nil,
    :lead_time => integer() | nil,
    :required_on_site_date => Date.t | nil,
    :scheduled_task => ProcoreV1API.Model.Task2.t | nil,
    :source_submittal_log_id => integer() | nil,
    :distributed_submittals => [ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOfDistributedSubmittalsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:actual_delivery_date, :date, nil, options)
    |> deserialize(:attachments, :list, ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner, options)
    |> deserialize(:confirmed_delivery_date, :date, nil, options)
    |> deserialize(:cost_code, :struct, ProcoreV1API.Model.TimesheetEntriesCostCode, options)
    |> deserialize(:distribution_members, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:required_on_site_date, :date, nil, options)
    |> deserialize(:scheduled_task, :struct, ProcoreV1API.Model.Task2, options)
    |> deserialize(:distributed_submittals, :list, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOfDistributedSubmittalsInner, options)
  end
end

