# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesIdPatchRequestPlanTemplateItemAssignee do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :is_holding,
    :verification_method_id
  ]

  @type t :: %__MODULE__{
    :is_holding => boolean() | nil,
    :verification_method_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesIdPatchRequestPlanTemplateItemAssignee do
  def decode(value, _options) do
    value
  end
end

