# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1ViewpointsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :bim_file_id,
    :view_folder_id,
    :created_at,
    :updated_at,
    :snapshot,
    :name,
    :camera_data,
    :redlines_data,
    :sections_data
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :bim_file_id => integer() | nil,
    :view_folder_id => integer() | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :snapshot => ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1ViewpointsInnerAllOf1Snapshot.t | nil,
    :name => String.t | nil,
    :camera_data => String.t | nil,
    :redlines_data => String.t | nil,
    :sections_data => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1ViewpointsInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:snapshot, :struct, ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1ViewpointsInnerAllOf1Snapshot, options)
  end
end

