# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdGenericToolsGenericToolIdStatusesPostRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :generic_tool_status
  ]

  @type t :: %__MODULE__{
    :generic_tool_status => ProcoreV1API.Model.GenericToolStatus.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdGenericToolsGenericToolIdStatusesPostRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:generic_tool_status, :struct, ProcoreV1API.Model.GenericToolStatus, options)
  end
end

