# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CoordinationIssueActivitiesFeedGet200ResponseInnerAnyOf do
  @moduledoc """
  Coordination Issue Assignment Activity
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :coordination_issue_id,
    :type,
    :details,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :coordination_issue_id => float() | nil,
    :type => String.t | nil,
    :details => ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetails.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CoordinationIssueActivitiesFeedGet200ResponseInnerAnyOf do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:details, :struct, ProcoreV1API.Model.CoordinationIssueAssignmentActivityDetails, options)
  end
end

