# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ChangeOrderPackagesPost201ResponseLineItemsInnerMarkupLineItemsInnerMarkup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :position,
    :markup_set,
    :name,
    :percentage,
    :compounds_markups_above,
    :created_at,
    :updated_at,
    :destination_cost_code,
    :destination_line_item_type,
    :desitination_budget_line_item_id,
    :destination_sub_job
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :position => integer() | nil,
    :markup_set => String.t | nil,
    :name => String.t | nil,
    :percentage => String.t | nil,
    :compounds_markups_above => boolean() | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :destination_cost_code => ProcoreV1API.Model.RestV10ChangeOrderPackagesPost201ResponseLineItemsInnerMarkupLineItemsInnerMarkupDestinationCostCode.t | nil,
    :destination_line_item_type => ProcoreV1API.Model.LineItemType3.t | nil,
    :desitination_budget_line_item_id => integer() | nil,
    :destination_sub_job => ProcoreV1API.Model.RestV10SubJobsGet200ResponseInner.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ChangeOrderPackagesPost201ResponseLineItemsInnerMarkupLineItemsInnerMarkup do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:destination_cost_code, :struct, ProcoreV1API.Model.RestV10ChangeOrderPackagesPost201ResponseLineItemsInnerMarkupLineItemsInnerMarkupDestinationCostCode, options)
    |> deserialize(:destination_line_item_type, :struct, ProcoreV1API.Model.LineItemType3, options)
    |> deserialize(:destination_sub_job, :struct, ProcoreV1API.Model.RestV10SubJobsGet200ResponseInner, options)
  end
end

