# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsGetDefaultResponseErrorDetailsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :message,
    :source
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :message => String.t,
    :source => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsGetDefaultResponseErrorDetailsInner do
  def decode(value, _options) do
    value
  end
end

