# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdActualProductionQuantitiesPostRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :actual_production_quantity
  ]

  @type t :: %__MODULE__{
    :actual_production_quantity => ProcoreV1API.Model.ActualProductionQuantity.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdActualProductionQuantitiesPostRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:actual_production_quantity, :struct, ProcoreV1API.Model.ActualProductionQuantity, options)
  end
end

