# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInner do
  @moduledoc """
  Work Order Contract
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounting_method,
    :actual_completion_date,
    :approval_letter_date,
    :approved_change_orders,
    :contract_date,
    :contract_start_date,
    :contract_estimated_completion_date,
    :created_at,
    :deleted_at,
    :description,
    :draft_change_orders_amount,
    :exclusions,
    :executed,
    :execution_date,
    :grand_total,
    :id,
    :inclusions,
    :issued_on_date,
    :letter_of_intent_date,
    :number,
    :origin_data,
    :origin_code,
    :origin_id,
    :pending_change_orders,
    :pending_revised_contract,
    :percentage_paid,
    :private,
    :project,
    :remaining_balance_outstanding,
    :requisitions_are_enabled,
    :retainage_percent,
    :returned_date,
    :revised_contract,
    :signed_contract_received_date,
    :show_line_items_to_non_admins,
    :status,
    :title,
    :total_draw_requests_amount,
    :total_payments,
    :total_requisitions_amount,
    :updated_at,
    :vendor,
    :currency_configuration
  ]

  @type t :: %__MODULE__{
    :accounting_method => String.t | nil,
    :actual_completion_date => Date.t | nil,
    :approval_letter_date => String.t | nil,
    :approved_change_orders => String.t | nil,
    :contract_date => Date.t | nil,
    :contract_start_date => Date.t | nil,
    :contract_estimated_completion_date => Date.t | nil,
    :created_at => DateTime.t | nil,
    :deleted_at => DateTime.t | nil,
    :description => String.t | nil,
    :draft_change_orders_amount => String.t | nil,
    :exclusions => String.t | nil,
    :executed => boolean() | nil,
    :execution_date => Date.t | nil,
    :grand_total => String.t | nil,
    :id => integer() | nil,
    :inclusions => String.t | nil,
    :issued_on_date => Date.t | nil,
    :letter_of_intent_date => Date.t | nil,
    :number => String.t | nil,
    :origin_data => String.t | nil,
    :origin_code => String.t | nil,
    :origin_id => String.t | nil,
    :pending_change_orders => String.t | nil,
    :pending_revised_contract => String.t | nil,
    :percentage_paid => String.t | nil,
    :private => boolean() | nil,
    :project => ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerProject.t | nil,
    :remaining_balance_outstanding => String.t | nil,
    :requisitions_are_enabled => boolean() | nil,
    :retainage_percent => String.t | nil,
    :returned_date => Date.t | nil,
    :revised_contract => String.t | nil,
    :signed_contract_received_date => Date.t | nil,
    :show_line_items_to_non_admins => boolean() | nil,
    :status => String.t | nil,
    :title => String.t | nil,
    :total_draw_requests_amount => String.t | nil,
    :total_payments => String.t | nil,
    :total_requisitions_amount => String.t | nil,
    :updated_at => DateTime.t | nil,
    :vendor => ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerVendor.t | nil,
    :currency_configuration => ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:actual_completion_date, :date, nil, options)
    |> deserialize(:contract_date, :date, nil, options)
    |> deserialize(:contract_start_date, :date, nil, options)
    |> deserialize(:contract_estimated_completion_date, :date, nil, options)
    |> deserialize(:execution_date, :date, nil, options)
    |> deserialize(:issued_on_date, :date, nil, options)
    |> deserialize(:letter_of_intent_date, :date, nil, options)
    |> deserialize(:project, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerProject, options)
    |> deserialize(:returned_date, :date, nil, options)
    |> deserialize(:signed_contract_received_date, :date, nil, options)
    |> deserialize(:vendor, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerVendor, options)
    |> deserialize(:currency_configuration, :struct, ProcoreV1API.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration, options)
  end
end

