# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV11DrawingAreasDrawingAreaIdDrawingsGet200ResponseInner do
  @moduledoc """
  Drawing
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :discipline,
    :number,
    :title,
    :obsolete,
    :current_revision
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :discipline => String.t | nil,
    :number => String.t | nil,
    :title => String.t | nil,
    :obsolete => boolean() | nil,
    :current_revision => ProcoreV1API.Model.RestV11DrawingAreasDrawingAreaIdDrawingsGet200ResponseInnerCurrentRevision.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV11DrawingAreasDrawingAreaIdDrawingsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:current_revision, :struct, ProcoreV1API.Model.RestV11DrawingAreasDrawingAreaIdDrawingsGet200ResponseInnerCurrentRevision, options)
  end
end

