# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10FoldersPostRequestFolder do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :parent_id,
    :name,
    :is_tracked,
    :explicit_permissions,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
    :parent_id => integer() | nil,
    :name => String.t,
    :is_tracked => boolean() | nil,
    :explicit_permissions => boolean() | nil,
    :"custom_field_%{custom_field_definition_id}" => ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10FoldersPostRequestFolder do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"custom_field_%{custom_field_definition_id}", :struct, ProcoreV1API.Model.IncidentWitnessStatementCreateParametersCustomFieldCustomFieldDefinitionId, options)
  end
end

