# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdBudgetChangesGet200Response do
  @moduledoc """
  Result set of budget change summary rows. Summary row doesn't contain all fields of a budget change.
  """

  @derive [Poison.Encoder]
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
    :data => [ProcoreV1API.Model.RestV10ProjectsProjectIdBudgetChangesGet200ResponseDataInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdBudgetChangesGet200Response do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdBudgetChangesGet200ResponseDataInner, options)
  end
end

