# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdTimeAndMaterialEntriesGet200ResponseInner do
  @moduledoc """
  Time and Material Entry
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :reference_number,
    :description,
    :status,
    :private,
    :number,
    :customer_signature_id,
    :company_signature_id,
    :project_id,
    :company_id,
    :location_id,
    :customer_id,
    :work_performed_on_date,
    :updated_at,
    :created_at,
    :deleted_at,
    :created_by_id
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :reference_number => String.t | nil,
    :description => String.t | nil,
    :status => integer() | nil,
    :private => boolean() | nil,
    :number => integer() | nil,
    :customer_signature_id => integer() | nil,
    :company_signature_id => integer() | nil,
    :project_id => integer() | nil,
    :company_id => integer() | nil,
    :location_id => integer() | nil,
    :customer_id => integer() | nil,
    :work_performed_on_date => String.t | nil,
    :updated_at => DateTime.t | nil,
    :created_at => DateTime.t | nil,
    :deleted_at => DateTime.t | nil,
    :created_by_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdTimeAndMaterialEntriesGet200ResponseInner do
  def decode(value, _options) do
    value
  end
end

