# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdBidPackagesBidPackageIdBidsPostRequestBid do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :vendor_id,
    :lump_sum_amount,
    :bidder_comments,
    :is_bidder_committed,
    :submitted,
    :recipient_ids
  ]

  @type t :: %__MODULE__{
    :vendor_id => integer(),
    :lump_sum_amount => float() | nil,
    :bidder_comments => String.t | nil,
    :is_bidder_committed => boolean() | nil,
    :submitted => boolean() | nil,
    :recipient_ids => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdBidPackagesBidPackageIdBidsPostRequestBid do
  def decode(value, _options) do
    value
  end
end

