# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdCorrespondenceTypesDefaultsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :correspondence_type_id,
    :description,
    :due_days,
    :distribution_members,
    :available_statuses,
    :statuses,
    :private_by_default,
    :workflows_enabled
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :correspondence_type_id => integer() | nil,
    :description => String.t | nil,
    :due_days => integer() | nil,
    :distribution_members => [ProcoreV1API.Model.RestV10ProjectsProjectIdTimesheetsPotentialTimesheetCreatorsGet200ResponseInner.t] | nil,
    :available_statuses => [String.t] | nil,
    :statuses => [ProcoreV1API.Model.RestV10ProjectsProjectIdCorrespondenceTypesDefaultsGet200ResponseInnerStatusesInner.t] | nil,
    :private_by_default => boolean() | nil,
    :workflows_enabled => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdCorrespondenceTypesDefaultsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:distribution_members, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdTimesheetsPotentialTimesheetCreatorsGet200ResponseInner, options)
    |> deserialize(:statuses, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdCorrespondenceTypesDefaultsGet200ResponseInnerStatusesInner, options)
  end
end

