# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ids,
    :attributes
  ]

  @type t :: %__MODULE__{
    :ids => [integer()],
    :attributes => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:attributes, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes, options)
  end
end

