# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10BimFilesGet200ResponseInnerAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :project_id,
    :company_id,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :project_id => float() | nil,
    :company_id => float() | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10BimFilesGet200ResponseInnerAllOf do
  def decode(value, _options) do
    value
  end
end

