# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10BimModelsGet200ResponseInnerOneOf1CurrentRevisionBimGridlineAllOf1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :gridline_file
  ]

  @type t :: %__MODULE__{
    :gridline_file => ProcoreV1API.Model.RestV10BimModelsGet200ResponseInnerOneOf1CurrentRevisionBimGridlineAllOf1GridlineFile.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10BimModelsGet200ResponseInnerOneOf1CurrentRevisionBimGridlineAllOf1 do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:gridline_file, :struct, ProcoreV1API.Model.RestV10BimModelsGet200ResponseInnerOneOf1CurrentRevisionBimGridlineAllOf1GridlineFile, options)
  end
end

