# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :actual_delivery_date,
    :attachments,
    :confirmed_delivery_date,
    :cost_code,
    :created_at,
    :custom_textarea_1,
    :custom_textfield_1,
    :deleted_at,
    :description,
    :design_team_review_time,
    :distribution_members,
    :internal_review_time,
    :lead_time,
    :required_on_site_date,
    :scheduled_task,
    :source_submittal_log_id,
    :distributed_submittals,
    :approvers,
    :attachments_count,
    :ball_in_court,
    :created_by,
    :current_revision,
    :distributed_at,
    :due_date,
    :formatted_number,
    :issue_date,
    :private,
    :received_date,
    :received_from,
    :responsible_contractor,
    :specification_section,
    :sub_job,
    :submit_by,
    :status,
    :type,
    :updated_at,
    :submittal_manager,
    :submittal_package,
    :location,
    :open_date,
    :custom_fields,
    :id,
    :number,
    :revision,
    :title
  ]

  @type t :: %__MODULE__{
    :actual_delivery_date => Date.t | nil,
    :attachments => [ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner.t] | nil,
    :confirmed_delivery_date => Date.t | nil,
    :cost_code => ProcoreV1API.Model.TimesheetEntriesCostCode.t | nil,
    :created_at => DateTime.t | nil,
    :custom_textarea_1 => String.t | nil,
    :custom_textfield_1 => String.t | nil,
    :deleted_at => DateTime.t | nil,
    :description => String.t | nil,
    :design_team_review_time => integer() | nil,
    :distribution_members => [ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t] | nil,
    :internal_review_time => integer() | nil,
    :lead_time => integer() | nil,
    :required_on_site_date => Date.t | nil,
    :scheduled_task => ProcoreV1API.Model.Task2.t | nil,
    :source_submittal_log_id => integer() | nil,
    :distributed_submittals => [ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOfDistributedSubmittalsInner.t] | nil,
    :approvers => [ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf1ApproversInner.t] | nil,
    :attachments_count => integer() | nil,
    :ball_in_court => [ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t] | nil,
    :created_by => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :current_revision => boolean() | nil,
    :distributed_at => DateTime.t | nil,
    :due_date => Date.t | nil,
    :formatted_number => String.t | nil,
    :issue_date => Date.t | nil,
    :private => boolean() | nil,
    :received_date => Date.t | nil,
    :received_from => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :responsible_contractor => ProcoreV1API.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor.t | nil,
    :specification_section => ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerSpecificationSection.t | nil,
    :sub_job => ProcoreV1API.Model.TimecardEntry2SubJob.t | nil,
    :submit_by => Date.t | nil,
    :status => ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerStatus.t | nil,
    :type => ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerType.t | nil,
    :updated_at => DateTime.t | nil,
    :submittal_manager => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :submittal_package => ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf1SubmittalPackage.t | nil,
    :location => ProcoreV1API.Model.Location.t | nil,
    :open_date => Date.t | nil,
    :custom_fields => ProcoreV1API.Model.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet200ResponseInnerCustomFields.t | nil,
    :id => integer() | nil,
    :number => String.t | nil,
    :revision => String.t | nil,
    :title => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201Response do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:actual_delivery_date, :date, nil, options)
    |> deserialize(:attachments, :list, ProcoreV1API.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner, options)
    |> deserialize(:confirmed_delivery_date, :date, nil, options)
    |> deserialize(:cost_code, :struct, ProcoreV1API.Model.TimesheetEntriesCostCode, options)
    |> deserialize(:distribution_members, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:required_on_site_date, :date, nil, options)
    |> deserialize(:scheduled_task, :struct, ProcoreV1API.Model.Task2, options)
    |> deserialize(:distributed_submittals, :list, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOfDistributedSubmittalsInner, options)
    |> deserialize(:approvers, :list, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf1ApproversInner, options)
    |> deserialize(:ball_in_court, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:created_by, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:due_date, :date, nil, options)
    |> deserialize(:issue_date, :date, nil, options)
    |> deserialize(:received_date, :date, nil, options)
    |> deserialize(:received_from, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:responsible_contractor, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWasteLogsGet200ResponseInnerVendor, options)
    |> deserialize(:specification_section, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerSpecificationSection, options)
    |> deserialize(:sub_job, :struct, ProcoreV1API.Model.TimecardEntry2SubJob, options)
    |> deserialize(:submit_by, :date, nil, options)
    |> deserialize(:status, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerStatus, options)
    |> deserialize(:type, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsGet200ResponseInnerType, options)
    |> deserialize(:submittal_manager, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:submittal_package, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdSubmittalsPost201ResponseAllOf1SubmittalPackage, options)
    |> deserialize(:location, :struct, ProcoreV1API.Model.Location, options)
    |> deserialize(:open_date, :date, nil, options)
    |> deserialize(:custom_fields, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet200ResponseInnerCustomFields, options)
  end
end

