# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdSpecificationSetsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :project_id,
    :company_id,
    :name,
    :created_at,
    :deleted_at,
    :updated_at,
    :date,
    :position
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :project_id => integer() | nil,
    :company_id => integer() | nil,
    :name => String.t | nil,
    :created_at => Date.t | nil,
    :deleted_at => Date.t | nil,
    :updated_at => Date.t | nil,
    :date => Date.t | nil,
    :position => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdSpecificationSetsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:created_at, :date, nil, options)
    |> deserialize(:deleted_at, :date, nil, options)
    |> deserialize(:updated_at, :date, nil, options)
    |> deserialize(:date, :date, nil, options)
  end
end

