# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200Response do
  @moduledoc """
  Bid Form
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :base_bid,
    :alternates
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :title => String.t | nil,
    :base_bid => [ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200ResponseBaseBidInner.t] | nil,
    :alternates => [ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200ResponseAlternatesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200Response do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:base_bid, :list, ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200ResponseBaseBidInner, options)
    |> deserialize(:alternates, :list, ProcoreV1API.Model.RestV10CompaniesCompanyIdBidBidIdBidFormsBidFormIdGet200ResponseAlternatesInner, options)
  end
end

