# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsIdValidationsPostRequestAttributes do
  @moduledoc """
  An object with configurable & custom field keys and values to be validated. This is for example purposes only.
  """

  @derive [Poison.Encoder]
  defstruct [
    :custom_field_47393,
    :custom_field_58238,
    :title,
    :number
  ]

  @type t :: %__MODULE__{
    :custom_field_47393 => String.t | nil,
    :custom_field_58238 => integer() | nil,
    :title => String.t | nil,
    :number => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsIdValidationsPostRequestAttributes do
  def decode(value, _options) do
    value
  end
end

