# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdGenericToolsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :domain_id,
    :title,
    :abbreviation,
    :private_by_default
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :domain_id => integer() | nil,
    :title => String.t | nil,
    :abbreviation => String.t | nil,
    :private_by_default => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdGenericToolsGet200ResponseInner do
  def decode(value, _options) do
    value
  end
end

