# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsGetDefaultResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => ProcoreV1API.Model.RestV10ProjectsGetDefaultResponseError.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsGetDefaultResponse do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:error, :struct, ProcoreV1API.Model.RestV10ProjectsGetDefaultResponseError, options)
  end
end

