# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdInvoicesAsyncJobsUuidGet200Response do
  @moduledoc """
  An Invoicing Async Job
  """

  @derive [Poison.Encoder]
  defstruct [
    :uuid,
    :company_id,
    :created_by_id,
    :status,
    :result,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :uuid => String.t | nil,
    :company_id => integer() | nil,
    :created_by_id => integer() | nil,
    :status => String.t | nil,
    :result => ProcoreV1API.Model.RestV10CompaniesCompanyIdInvoicesAsyncJobsUuidGet200ResponseResult.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdInvoicesAsyncJobsUuidGet200Response do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:result, :struct, ProcoreV1API.Model.RestV10CompaniesCompanyIdInvoicesAsyncJobsUuidGet200ResponseResult, options)
  end
end

