# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :class_name,
    :fields,
    :project_ids,
    :category,
    :action_plan_type_id,
    :inspection_type_id,
    :generic_tool_id,
    :company_default,
    :company_configurable_field_set_default_column_name
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :class_name => String.t,
    :fields => ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSetFields.t,
    :project_ids => [integer()] | nil,
    :category => String.t | nil,
    :action_plan_type_id => integer() | nil,
    :inspection_type_id => integer() | nil,
    :generic_tool_id => integer() | nil,
    :company_default => boolean() | nil,
    :company_configurable_field_set_default_column_name => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSet do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :struct, ProcoreV1API.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSetFields, options)
  end
end

