# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdChecklistSchedulesCalculateTotalInspectionsCountGetRequestSchedule do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :starts_at,
    :ends_at,
    :frequency
  ]

  @type t :: %__MODULE__{
    :starts_at => DateTime.t,
    :ends_at => DateTime.t,
    :frequency => String.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdChecklistSchedulesCalculateTotalInspectionsCountGetRequestSchedule do
  def decode(value, _options) do
    value
  end
end

