# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedProcoreItemsInnerAllOf1ItemData do
  @moduledoc """
  This field shows data specific to the associated item. If item type is RFI, it will contain attribute subject, number, and has_official_response
  """

  @derive [Poison.Encoder]
  defstruct [
    :has_official_response,
    :subject,
    :number
  ]

  @type t :: %__MODULE__{
    :has_official_response => boolean() | nil,
    :subject => String.t | nil,
    :number => String.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOf1LinkedProcoreItemsInnerAllOf1ItemData do
  def decode(value, _options) do
    value
  end
end

