# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleLookaheadsGet200ResponseInner do
  @moduledoc """
  Schedule Lookahead
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :start_date,
    :end_date
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :start_date => DateTime.t | nil,
    :end_date => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleLookaheadsGet200ResponseInner do
  def decode(value, _options) do
    value
  end
end

