# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :requested_changes
  ]

  @type t :: %__MODULE__{
    :requested_changes => [ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequestRequestedChangesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requested_changes, :list, ProcoreV1API.Model.RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequestRequestedChangesInner, options)
  end
end

