# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlanItemAssigneesPostRequestPlanItemAssignee do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :plan_item_id,
    :is_holding,
    :party_id,
    :role,
    :verification_method_id
  ]

  @type t :: %__MODULE__{
    :plan_item_id => integer(),
    :is_holding => boolean() | nil,
    :party_id => integer() | nil,
    :role => String.t | nil,
    :verification_method_id => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdActionPlansPlanItemAssigneesPostRequestPlanItemAssignee do
  def decode(value, _options) do
    value
  end
end

