# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RestV10ProjectsProjectIdCallLogsGet200ResponseInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created_at,
    :date,
    :datetime,
    :deleted_at,
    :subject_to,
    :subject_from,
    :description,
    :start_hour,
    :start_minute,
    :end_hour,
    :end_minute,
    :permissions,
    :position,
    :updated_at,
    :created_by,
    :attachments
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :created_at => DateTime.t | nil,
    :date => Date.t | nil,
    :datetime => DateTime.t | nil,
    :deleted_at => DateTime.t | nil,
    :subject_to => String.t | nil,
    :subject_from => String.t | nil,
    :description => String.t | nil,
    :start_hour => integer() | nil,
    :start_minute => integer() | nil,
    :end_hour => integer() | nil,
    :end_minute => integer() | nil,
    :permissions => ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions.t | nil,
    :position => integer() | nil,
    :updated_at => DateTime.t | nil,
    :created_by => ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t | nil,
    :attachments => [ProcoreV1API.Model.RestV10ProjectsProjectIdNotesLogsGet200ResponseInnerAttachmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RestV10ProjectsProjectIdCallLogsGet200ResponseInner do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
    |> deserialize(:permissions, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdVisitorLogsGet200ResponseInnerPermissions, options)
    |> deserialize(:created_by, :struct, ProcoreV1API.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy, options)
    |> deserialize(:attachments, :list, ProcoreV1API.Model.RestV10ProjectsProjectIdNotesLogsGet200ResponseInnerAttachmentsInner, options)
  end
end

