# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.RfiUpdateBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rfi
  ]

  @type t :: %__MODULE__{
    :rfi => ProcoreV1API.Model.RfiUpdateBodyRfi.t
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.RfiUpdateBody do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rfi, :struct, ProcoreV1API.Model.RfiUpdateBodyRfi, options)
  end
end

