# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.SpecificationSectionRevision do
  @moduledoc """
  A version of a Specification Section. Each time a Specification Section is revised, the newly uploaded version is a new revision of that section.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :specification_section_id,
    :specification_section_division_id,
    :specification_set_id,
    :number,
    :description,
    :url,
    :revision,
    :issued_date,
    :received_date,
    :updated_at,
    :custom_fields
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :specification_section_id => integer() | nil,
    :specification_section_division_id => integer() | nil,
    :specification_set_id => integer() | nil,
    :number => String.t | nil,
    :description => String.t | nil,
    :url => String.t | nil,
    :revision => String.t | nil,
    :issued_date => Date.t | nil,
    :received_date => Date.t | nil,
    :updated_at => String.t | nil,
    :custom_fields => ProcoreV1API.Model.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet200ResponseInnerCustomFields.t | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.SpecificationSectionRevision do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:issued_date, :date, nil, options)
    |> deserialize(:received_date, :date, nil, options)
    |> deserialize(:custom_fields, :struct, ProcoreV1API.Model.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet200ResponseInnerCustomFields, options)
  end
end

