# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.TotalInspections do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :total_in_schedule
  ]

  @type t :: %__MODULE__{
    :total_in_schedule => integer() | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.TotalInspections do
  def decode(value, _options) do
    value
  end
end

