# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ProcoreV1API.Model.Upload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :response_filename,
    :response_content_type,
    :segments
  ]

  @type t :: %__MODULE__{
    :response_filename => String.t | nil,
    :response_content_type => String.t | nil,
    :segments => [ProcoreV1API.Model.UploadSegmentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ProcoreV1API.Model.Upload do
  import ProcoreV1API.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:segments, :list, ProcoreV1API.Model.UploadSegmentsInner, options)
  end
end

